export const SET_MAIN_TAB = 'ROUTER:SET_MAIN_TAB';

export const LOAD_FONTS_REQUEST = 'UI:LOAD_FONTS_REQUEST';
export const LOAD_FONTS_SUCCESS = 'UI:LOAD_FONTS_SUCCESS';
export const LOAD_FONTS_FAILURE = 'UI:LOAD_FONTS_FAILURE';

export const SET_LOCALE_REQUEST = 'I18N:SET_LOCALE_REQUEST';
export const SET_LOCALE_SUCCESS = 'I18N:SET_LOCALE_SUCCESS';
export const SET_LOCALE_FAILURE = 'I18N:SET_LOCALE_FAILURE';
export const LOAD_CURRENT_LOCALE_REQUEST = 'I18N:LOAD_CURRENT_LOCALE_REQUEST';
export const LOAD_CURRENT_LOCALE_SUCCESS = 'I18N:LOAD_CURRENT_LOCALE_SUCCESS';
export const LOAD_CURRENT_LOCALE_FAILURE = 'I18N:LOAD_CURRENT_LOCALE_FAILURE';

export const SELECT_ANSWER = 'QUESTIONNAIRE:SELECT_ANSWER';

export const PREFERENCES_CURRENT_LOCALE_CODE = 'PREFERENCES:CURRENT_LOCALE_CODE';