export const SET_COUNTER = 'COUNTER:SET_COUNTER';
export const RESET_COUNTER = 'COUNTER:RESET_COUNTER';

export const SET_MESSAGE_TEXT = 'MESSAGE:SET_MESSAGE';

export const SET_MAIN_TAB = 'ROUTER:SET_MAIN_TAB';
