export const SET_QUESTIONNAIRE_PAGE = 'ROUTER:SET_QUESTIONNAIRE_PAGE';
export const SET_PLAN_PAGE = 'ROUTER:SET_PLAN_PAGE';
export const SET_EXPLORE_PAGE = 'ROUTER:SET_EXPLORE_PAGE';

export const LOAD_FONTS_REQUEST = 'UI:LOAD_FONTS_REQUEST';
export const LOAD_FONTS_SUCCESS = 'UI:LOAD_FONTS_SUCCESS';
export const LOAD_FONTS_FAILURE = 'UI:LOAD_FONTS_FAILURE';

export const SET_LOCALE_REQUEST = 'I18N:SET_LOCALE_REQUEST';
export const SET_LOCALE_SUCCESS = 'I18N:SET_LOCALE_SUCCESS';
export const SET_LOCALE_FAILURE = 'I18N:SET_LOCALE_FAILURE';
export const LOAD_CURRENT_LOCALE_REQUEST = 'I18N:LOAD_CURRENT_LOCALE_REQUEST';
export const LOAD_CURRENT_LOCALE_SUCCESS = 'I18N:LOAD_CURRENT_LOCALE_SUCCESS';
export const LOAD_CURRENT_LOCALE_FAILURE = 'I18N:LOAD_CURRENT_LOCALE_FAILURE';

export const SELECT_ANSWER = 'QUESTIONNAIRE:SELECT_ANSWER';

export namespace Task {
  export const ADD_TO_SAVED_LIST = 'TASK:ADD_TO_SAVED_LIST';
  export const REMOVE_FROM_SAVED_LIST = 'TASK:REMOVE_FROM_SAVED_LIST';
  export const ADD_TO_SUGGESTED_LIST = 'TASK:ADD_TO_SUGGESTED_LIST';
  export const REMOVE_FROM_SUGGESTED_LIST = 'TASK:REMOVE_FROM_SUGGESTED_LIST';
  export const TOGGLE_COMPLETED = 'TASK:TOGGLE_COMPLETED';
  export const TOGGLE_STARRED = 'TASK:TOGGLE_STARRED';
  export const SHARE = 'TASK:SHARE';
}

export const PREFERENCES_LOCALE_CODE = 'PREFERENCES:LOCALE_CODE';
